---
title: "FWT: Fire-Weather Typing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 10, fig.height = 10, cache = TRUE, cache.path = "cache/")
```

# PCA

## Parameters
```{r parameters}
years <- 1970:2021
lonLim <- c(-9.5, 4.3)
latLim <- c(36, 44)
dataset <- "ERA5Land"
```

## Library
```{r library, cache=FALSE, message=FALSE, results='hide'}
library(visualizeR)
devtools::load_all("transformeR") # instead of library(transformeR)
source("load_data.R")
```

## Load data and compute PCA
```{r pca, cache=FALSE}
if (file.exists("data/pca_isi_bui.rds")) {
  pca <- readRDS("data/pca_isi_bui.rds")
} else {
  dat_era_isi <- load_data(year = years, lonLim = lonLim, latLim = latLim, what = "ISI", dataset = dataset)
  dat_era_bui <- load_data(year = years, lonLim = lonLim, latLim = latLim, what = "BUI", dataset = dataset)

  multigrid <- makeMultiGrid(dat_era_isi, dat_era_bui)
  pca <- prinComp(multigrid, v.exp = c(.95), which.combine = c("ISI", "BUI"),
                keep.orig = FALSE, imputation = FALSE)

  saveRDS(pca, "data/pca_isi_bui.rds")
}
```

## Explained variance
```{r time_explained_variance, fig.width=9, fig.height=6, dpi=300, fig.path="figures/"}
explained_variance_combined <- attr(pca$COMBINED[[1]], "explained_variance")
plot(explained_variance_combined, type = "b", xlab = "Number of Principal Components", ylab = "Explained Variance (%)", main = "Explained variance")
```

# fire-weather typing
```{r}
set.seed(123)
n <- 10
c <- lapply(2:n, function(k) {
  kmeans(pca$COMBINED[[1]]$PCs, centers = k, nstart = 5, iter.max = 100)
})
```

```{r time_tss, fig.width=9, fig.height=6, dpi=300, fig.path="figures/"}
plot(
  2:n, sapply(c, function(k) k$tot.withinss),
  type = "b",
  pch = 19,
  xlab = "Number of clusters K",
  ylab = "Total within-cluster sum of squares"
)
```

```{r order}
date <- attr(pca, "dates_start")
year <- as.integer(format(as.POSIXct(date, tz="GMT"), "%Y"))

dat_era_fwi <- load_data(year = years, lonLim = lonLim, latLim = latLim, what = "FWI", dataset = dataset)

cl <- c[[5]]$cluster # 6

# reorder by FWI
x <- apply(dat_era_fwi$Data, 1, mean, na.rm = TRUE)
m <- tapply(x, cl, mean)
o <- order(m)
cl <- match(cl, o)

rm(dat_era_fwi)
```

```{r time_clusters, fig.width=9, fig.height=6, dpi=300, fig.path="figures/"}
# build matrix (rows = years)
mat <- matrix(NA, nrow=length(years), ncol=max(table(year)))

for (i in seq_along(years)) {
  idx <- which(year == years[i])
  mat[i, 1:length(idx)] <- cl[idx]
}

cols <-  c("#3288BD", "#66C2A5", "#E6F598",  "#F46D43", "#9E0142", "#E91E8C")

image(1:nrow(mat), 1:ncol(mat),
      mat,
      col = cols,
      axes = FALSE,
      xlab = "Year",
      ylab = "Day of year")

axis(1, at = 1:length(years), labels = years)
axis(2, at = seq(0, ncol(mat), by = 50), labels = seq(0, ncol(mat), by = 50))

legend("top",
       inset = c(0, -0.1),
       xpd = TRUE,
       horiz = TRUE,
       legend = paste0("Cl", seq_along(unique(cl))),
       fill = cols,
       bty = "n")
```

## mean of FWI in each cluster

```{r}
boxplot(
  x ~ cl,
  xlab = "Cluster",
  ylab = "Spatial mean FWI",
  col = cols
)
legend("topleft", legend=paste("Cl", 1:length(unique(cl))), fill=cols, cex=0.8)
```

## mean BUI and ISI for each cluster

```{r}
# ISI
dat_era_isi <- load_data(year = years, lonLim = lonLim, latLim = latLim, what = "ISI", dataset = dataset)
y <- apply(dat_era_isi$Data, 1, mean, na.rm = TRUE)
rm(dat_era_isi)

boxplot(
  y ~ cl,
  xlab = "Cluster",
  ylab = "Spatial mean ISI",
  col = cols
)
legend("topleft", legend=paste("Cl", 1:length(unique(cl))), fill=cols, cex=0.8)
```

```{r}
# BUI
dat_era_bui <- load_data(year = years, lonLim = lonLim, latLim = latLim, what = "BUI", dataset = dataset)
z <- apply(dat_era_bui$Data, 1, mean, na.rm = TRUE)
rm(dat_era_bui)

boxplot(
  z ~ cl,
  xlab = "Cluster",
  ylab = "Spatial mean BUI",
  col = cols
)
legend("topleft", legend=paste("Cl", 1:length(unique(cl))), fill=cols, cex=0.8)
```

# mean FWI, ISI and BUI for each cluster
```{r time_boxplots, fig.width=12, fig.height=5, dpi=300, fig.path="figures/"}
# pdf("~/figure/time_boxplots.pdf", width = 12, height = 5)
par(mfrow = c(1, 3), mar = c(4, 4, 3, 1))

# FWI
boxplot(x ~ cl, xlab = "Cluster", ylab = "Spatial mean FWI", col = cols, main = "FWI")

# ISI
boxplot(y ~ cl, xlab = "Cluster", ylab = "Spatial mean ISI", col = cols, main = "ISI")

# BUI
boxplot(z ~ cl, xlab = "Cluster", ylab = "Spatial mean BUI", col = cols, main = "BUI")
```

```{r}
plot(pca$COMBINED[[1]]$PCs[, 1], pca$COMBINED[[1]]$PCs[, 2], col = cols[cl], xlab = "PC1", ylab = "PC2")
```

# save
```{r}
saveRDS(list(cl = cl, date = date) , "data/fwt_typing.rds")
```


