---
title: "FWR: Fire-Weather Regions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 10, fig.height = 8, cache = TRUE)
```

## Parameters
```{r parameters}
years <- 1970:2021
lonLim <- c(-9.5, 4.3)
latLim <- c(36, 44)
dataset <- "ERA5Land"
```

## Library
```{r library, cache=FALSE, message=FALSE, results='hide'}
library(visualizeR)
devtools::load_all("transformeR") # instead of library(transformeR) #del
source("load_data.R")
```

## PCA
```{r}
# ISI
dat_era_isi <- load_data(year = years, lonLim = lonLim, latLim = latLim, what = "ISI", dataset = dataset)
clim <- climatology(dat_era_isi)
# BUI
dat_era_bui <- load_data(year = years, lonLim = lonLim, latLim = latLim, what = "BUI", dataset = dataset)

# convert to ("time", "point")
data_isi <- matrix(dat_era_isi$Data, nrow = dim(dat_era_isi$Data)[1])
data_bui <- matrix(dat_era_bui$Data, nrow = dim(dat_era_bui$Data)[1])

rm(dat_era_isi)
rm(dat_era_bui)

# remove points with NA values
keep_points <- which(colSums(is.na(data_isi)) == 0)
data_isi <- t(data_isi[, keep_points])
data_bui <- t(data_bui[, keep_points])

# scale data
data_isi <- scale(data_isi)
data_bui <- scale(data_bui)

# combine ISI and BUI
data_combined <- cbind(data_isi, data_bui)
rm(data_isi, data_bui)

# compute PCA
pca_combined <- prcomp(data_combined, center = TRUE, scale. = TRUE)

rm(data_combined)
```

## explained variance
```{r region_explained_variance, fig.width=9, fig.height=6, dpi=300, fig.path="figures/"}
pca_combined_var <- pca_combined$sdev^2
pca_combined_var_explained <- pca_combined_var / sum(pca_combined_var)
cumulative_var_explained <- cumsum(pca_combined_var_explained)

plot(cumulative_var_explained[1:which(cumulative_var_explained >= 0.95)[1]], type = "b", xlab = "Number of Principal Components", ylab = "Cumulative Variance Explained", main = "PCA Variance Explained")
```


```{r}
num_components <- which(cumulative_var_explained >= 0.95)[1]
pca_combined_reduced <- pca_combined$x[, 1:num_components]
num_components
```

```{r region_tss, fig.width=9, fig.height=6, dpi=300, fig.path="figures/"}
clusters_to_grid <- function(cluster, keep_points, grid_dim) {
  cluster_full <- rep(NA_integer_, prod(grid_dim))
  cluster_full[keep_points] <- cluster
  array(cluster_full, dim = grid_dim)
}

grid_dim <- dim(clim$Data)[-1]
wcss <- numeric(9)
set.seed(123)

kms <- list()
for (k in 2:10) {
  km <- kmeans(pca_combined_reduced, centers = k, nstart = 25)
  clim_plot <- clim
  clim_plot$Data[1,,] <- clusters_to_grid( km$cluster, keep_points, grid_dim)
  # spatialPlot(clim_plot, backdrop.theme = "countries", main = paste("Clusters of ISI and BUI with k =", k) )
  wcss[k - 1] <- km$tot.withinss
  
  kms[[k]] <- clim_plot
}

plot(2:10, wcss, type = "b", xlab = "Number of Clusters (k)", ylab = "Total Within-Cluster Sum of Squares")

saveRDS(kms, "data/kmeans_results.rds")
```

```{r region_clusters, fig.width=13, fig.height=8, dpi=300, fig.path="figures/"}
kmeans_all <- readRDS("data/kmeans_results.rds")
kmeans_all <- kmeans_all[-1]
names(kmeans_all) <- paste0("k", 2:10)

library(gridExtra)
library(grid)
library(RColorBrewer)

base_cols <- brewer.pal(8, "Set2")
extra_cols <-  c("#6EB4D4", "#C49FD4")

plots <- lapply(2:10, function(K) {
  
  cols <- c(base_cols, extra_cols)[1:K]
  
  spatialPlot(
    kmeans_all[[paste0("k", K)]],
    backdrop.theme = "countries",
    col.regions = cols,
    at = seq(0.5, K + 0.5, 1),
    colorkey = list(
      labels = list(
        at = 1:K,
        labels = 1:K
      )
    )
  )
  
})

grid.arrange(
  grobs = plots,
  ncol = 3,
  nrow = 3
)
```



```{r save}
clim <- kms[[3]]

saveRDS(clim, "data/region_k3.rds")
```

```{r}
library(raster)
library(terra)

region_obj <- readRDS("data/region_k3.rds")

# Create raster from cluster grid
r <- raster(
  nrows = length(region_obj$xyCoords$y),
  ncols = length(region_obj$xyCoords$x),
  xmn   = min(region_obj$xyCoords$x) - 0.05,
  xmx   = max(region_obj$xyCoords$x) + 0.05,
  ymn   = min(region_obj$xyCoords$y) - 0.05,
  ymx   = max(region_obj$xyCoords$y) + 0.05,
  crs   = CRS("+proj=longlat +datum=WGS84")
)

values(r) <- as.vector(t(drop(region_obj$Data)[nrow(drop(region_obj$Data)):1, ]))

r <- rast(r)

# Convert each cluster to a dissolved polygon
cluster_polys <- lapply(1:3, function(k) {
  r_k <- r
  r_k[r_k != k] <- NA
  as.polygons(r_k, dissolve = TRUE)
})

clusters <- do.call(rbind, cluster_polys)
clusters$name <- c("N", "E", "SW")

# Smooth boundaries
clusters <- simplifyGeom(clusters, tolerance = 0.1)

# Save shapefile
writeVector(clusters, "data/cluster_regions.shp", overwrite = TRUE)
```

```{r}
library(sp)
library(raster)
library(terra)

clusters_sp <- as(vect("data/cluster_regions.shp"), "Spatial")
K <- 3
print(spatialPlot(clim,
                  backdrop.theme = "countries",
                  main           = "Clusters of ISI and BUI with k = 3",
                  col.regions    = c(base_cols, extra_cols)[1:K],
                  at             = seq(0.5, K + 0.5, 1),
                  colorkey       = list(labels = list(at= 1:K,labels = 1:K)),
                  sp.layout      = list(list(clusters_sp, first = FALSE, col = "black", lwd = 1.5))))
```
